#logging:
#  level:
#    root: DEBUG
jwt:
  secret: mySecretKey
  expiration: 86400000

server:
  port: 8080

spring:
  application:
    name: msvc-auth


  datasource:
        #url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: root.123*
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Keep the connection alive if idle for a long time (needed in production)
  #spring.datasource.testWhileIdle=true
  #spring.datasource.validationQuery=SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
